//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public long ContractId { get; set; }
        public Nullable<long> EmployeeId { get; set; }
        public Nullable<System.DateTime> SignTime { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> RenewCount { get; set; }
        public Nullable<double> ProbationarySalary { get; set; }
        public Nullable<double> OfficialSalary { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
