//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public string CourseCode { get; set; }
        public string CourseName { get; set; }
        public Nullable<long> DepartmentId { get; set; }
        public string StudentType { get; set; }
        public Nullable<int> Hours { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> AccruedCount { get; set; }
        public Nullable<int> AttendedCount { get; set; }
        public string CourseRemark { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
