//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Contract = new HashSet<Contract>();
            this.Wage = new HashSet<Wage>();
        }
    
        public long EmployeeId { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public Nullable<long> DepartmentId { get; set; }
        public Nullable<long> PositionId { get; set; }
        public Nullable<System.DateTime> DateIntoCompany { get; set; }
        public string Phone { get; set; }
        public string QQ { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string IDCard { get; set; }
        public string School { get; set; }
        public string Remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract> Contract { get; set; }
        public virtual Department Department { get; set; }
        public virtual Position Position { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wage> Wage { get; set; }
    }
}
