//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Contract = new HashSet<Contract>();
            this.Wage = new HashSet<Wage>();
        }

        [Display(Name = "员工ID")]
        public long EmployeeId { get; set; }
        [Display(Name = "姓名")]
        public string Name { get; set; }
        [Display(Name = "性别")]
        public string Sex { get; set; }
        [Display(Name = "部门ID")]
        public Nullable<long> DepartmentId { get; set; }
        [Display(Name = "职位ID")]
        public Nullable<long> PositionId { get; set; }
        [Display(Name = "进入公司时间")]
        public Nullable<System.DateTime> DateIntoCompany { get; set; }
        [Display(Name = "电话")]
        public string Phone { get; set; }
        [Display(Name = "QQ")]
        public string QQ { get; set; }
        [Display(Name = "家庭地址")]
        public string Address { get; set; }
        [Display(Name = "邮箱")]
        public string Email { get; set; }
        [Display(Name = "身份证")]
        public string IDCard { get; set; }
        [Display(Name = "毕业学校")]
        public string School { get; set; }
        [Display(Name = "备注")]
        public string Remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract> Contract { get; set; }
        public virtual Department Department { get; set; }
        public virtual Position Position { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wage> Wage { get; set; }
    }
}
